database:
  username: root
  password: "zss123456zss"
  host: 127.0.0.1
  port: 3306
  dbname: gva
  charset: utf8mb4 

fisco:
  is_sm_crypto: false
  group_id: "group0"
  disable_ssl: false
  host: "127.0.0.1"
  port: 20200
  tls_ca_file: "./config/sdk/ca.crt"
  tls_key_file: "./config/sdk/sdk.key"
  tls_cert_file: "./config/sdk/sdk.crt"

contract:
  key_share_contract: "0x0102e8b6fc8cdf9626fddc1c3ea8c1e79b3fce94"
  decision_contract: "0x33e56a083e135936c1144960a708c43a661706c0"
